# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ips_to_xy <- function(ips, addr_space_bits_per_image = 32L, addr_space_bits_per_pixel = 8L) {
    .Call('_hilbertv4_ips_to_xy', PACKAGE = 'hilbertv4', ips, addr_space_bits_per_image, addr_space_bits_per_pixel)
}

