# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bounding box from CIDR blocks
#'
#' Returns a data frame of bounding boxes for a given CIDR within the
#' Hilbert-curve plane.
#'
#' @md
#' @param cidr character vector of dotted-decimal/digit CIDRs
#' @return list of bounding box extents for each CIDR - `cidr`,
#'         `xmin`, `ymin`, `xmax`, `ymax`
#' @export
#' @examples
#' bbox_cidr("30.0.0.0/8")
bbox_cidr <- function(cidr, addr_space_bits_per_image = 32L, addr_space_bits_per_pixel = 8L) {
    .Call('_hilbertv4_bbox_cidr', PACKAGE = 'hilbertv4', cidr, addr_space_bits_per_image, addr_space_bits_per_pixel)
}

ips_to_xy <- function(ips, addr_space_bits_per_image = 32L, addr_space_bits_per_pixel = 8L) {
    .Call('_hilbertv4_ips_to_xy', PACKAGE = 'hilbertv4', ips, addr_space_bits_per_image, addr_space_bits_per_pixel)
}

